#
#	@(#)Makefile (testing binary for bchan)
#		GNU make 用
#
#	make の方法
#	・make
#		リリース用の正式版を作成
#	・make mode=debug
#		デバッグ用に作成
#	・make clean
#		make で作成した全てのファイルを削除
#	・make install
#		規定の場所にインストール (実機用のみ)
#

# バージョン
version = 0x0010

# リリース用をデフォルトにする
mode =

# ソースの依存関係ファイル (自動生成)
DEPS = Dependencies
DEPENDENCIES_OUTPUT := $(DEPS)

# アプリケーション標準ルール
include ../../etc/makerules

#----------------------------------------------------------------------
# 作成対象
TARGET = bchan_test

# ソースファイルのサーチパス
S = ../src ../src/bchanf/src/unittest
VPATH = $(S)

# ヘッダファイルのディレクトリ追加
HEADER := $(S) $(HEADER) ../src/bchanf/src

# ソースファイル
SRC =	test_main.c unittest_driver.c cache.c test_cache.c parser.c test_parser.c layout.c test_layout.c retriever.c tadlib.c parselib.c test_parselib.c http.c submitutil.c test_submitutil.c sjisstring.c test_sjisstring.c residhash.c test_residhash.c resindexhash.c test_resindexhash.c postres.c test_postres.c tadimf.c test_tadimf.c layoutarray.c test_layoutarray.c layoutstyle.c wordlist.c test_wordlist.c tadsearch.c test_tadsearch.c httpheaderlexer.c test_httpheaderlexer.c setcookieheader.c test_setcookieheader.c httpdateparser.c test_httpdateparser.c cookiedb.c test_cookiedb.c psvlexer.c test_psvlexer.c

# データボックスソースファイル
DBSRC =

SRC += $(DBSRC)

WC_SRC = $(filter %.C, $(SRC))

# オブジェクトファイル
OBJ = $(addsuffix .o, $(basename $(SRC)))

# コンパイルオプション
ifneq ($(mode), debug)
  CFLAGS += -Wall
endif

CFLAGS += $(BUILDOPTIONS) -DBCHAN_CONFIG_DEBUG

LOADLIBES += -limg

#----------------------------------------------------------------------
.PHONY: all clean install

INST = $(addprefix $(TARGET), .map)
NOINST = $(addprefix $(TARGET), .out)

all: library $(INST)

library:
	@$(MAKE) -f Makefile.lib -C ./bchanf

$(TARGET).out: $(OBJ) bchanf/libbchanf.a
	$(LINK.o) $(LDOBJS) $^ $(LOADLIBES) $(LDLIBS) $(OUTPUT_OPTION)

clean:
	@$(MAKE) clean -f Makefile.lib -C ./bchanf
	$(RM) $(OBJ)
	$(RM) $(WC_SRC:%.C=%.c) $(DBSRC)
	$(RM) $(INST) $(NOINST) *.lst $(DEPS)

install: $(INST:%=$(EXE_INSTALLDIR)/%)

$(EXE_INSTALLDIR)/$(TARGET).out: $(EXE_INSTALLDIR)/%: %
	$(EXE_INSTALL_STRIP)

# ソースの依存関係

$(WC_SRC:%.C=%.c):

$(DBSRC):

ifdef DEPENDENCIES_OUTPUT
$(DEPS):	; touch $(DEPS)
else
$(DEPS): $(SRC)	; $(MAKEDEPS) $@ $?
endif

include $(DEPS)
